const cadastroMatrizes = [
  {
    id: 1,
    nome: 'Açoita Cavalo',
    nomeCientifico: 'Luehea divaricata Mart & Zucc.',
    matriz: 'M 2082',
    bioma: 'Cerrado, Mata Atlântica e Pampa',
    conservacao: ' Pouco preocupante',
    classe: 'Secundária',
    coleta: 'Mai-Ago',
    link: '/acoita',
    gps: "https://www.google.com.br/maps/place/23%C2%B023'17.2%22S+47%C2%B037'09.5%22W/@-23.3880778,-47.6197675,166m/data=!3m1!1e3!4m5!3m4!1s0x0:0x7aa73cbc8955f778!8m2!3d-23.3881!4d-47.6193",
    mudaDesc:
      'Mudas de Açoita Cavalo - Atinge Porte médio adequado em 6 meses.',
    mudaImg: 'https://i.imgur.com/4Z4ZQ8M.jpg',
    sementeDes: 'Sementes de Açoita Cavalo podem ter cerca de 1 cm.',
    sementeImg: 'https://i.imgur.com/4Z4ZQ8M.jpg',
    arvoreDesc: 'Árvores de Açoita Cavalo podem ter cerca de 30 m.',
    arvoreImg: 'https://i.imgur.com/4Z4ZQ8M.jpg',
    florDesc: 'A Flor do Açoita cavalo floresce no periodo de Maio a Agosto.',
    florImg: 'https://i.imgur.com/4Z4ZQ8M.jpg'
  },
  {
    id: 2,
    nome: 'Amendoim Bravo',
    nomeCientifico: 'Platypodium elegans Vog.',
    matriz: 'M 909',
    bioma: 'Cerrado e Pantanal',
    conservacao: ' Pouco preocupante',
    classe: 'Secundária',
    coleta: 'Set-Nov',
    link: '/amendoin',
    gps: "https://www.google.com.br/maps/place/23%C2%B023'17.5%22S+47%C2%B037'43.3%22W/@-23.3881951,-47.6312749,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-23.3882!4d-47.6287",
    mudaDesc: 'Mudas de Amendoim Bravo emergem entre 15 -25 dias .',
    mudaImg: 'https://i.imgur.com/4Z4ZQ8M.jpg',
    sementeDes: 'Sementes de Amendoim Bravo podem ter cerca de 3 cm.',
    sementeImg: 'https://i.imgur.com/4Z4ZQ8M.jpg',
    arvoreDesc: 'Árvores de XXX podem ter cerca de 8 a 12 m.',
    arvoreImg: 'https://i.imgur.com/4Z4ZQ8M.jpg',
    florDesc: 'A Flor do XXX floresce no periodo de Maio a Agosto.',
    florImg: 'https://i.imgur.com/4Z4ZQ8M.jpg'
  },
  {
    id: 3,
    nome: 'Copaíba',
    nomeCientifico: 'Copaifera IBngsdorlfii Oesf.',
    matriz: 'M 248',
    bioma: 'Cerrado, Mata Atlântica.',
    conservacao: 'Pouco Preocupante',
    classe: 'Clímax',
    coleta: 'Ago-Set',
    link: '/copaiba',
    gps: "https://www.google.com.br/maps/place/23%C2%B023'08.9%22S+47%C2%B037'13.7%22W/@-23.3857941,-47.6230512,17z/data=!3m1!4b1!4m4!3m3!8m2!3d-23.385799!4d-47.6204763",
    mudaDesc: 'Mudas de Copaíba atinge Porte médio adequado em 6 meses .',
    mudaImg: 'https://i.imgur.com/4Z4ZQ8M.jpg',
    sementeDes: 'Sementes de Copaiba podem ter cerca de 1 cm.',
    sementeImg: 'https://i.imgur.com/4Z4ZQ8M.jpg',
    arvoreDesc: 'Árvores de Copaíba podem ter cerca de 10-15 m.',
    arvoreImg: 'https://i.imgur.com/4Z4ZQ8M.jpg',
    florDesc: 'A Flor da ZXXXX floresce no periodo de Maio a Agosto.',
    florImg: 'https://i.imgur.com/4Z4ZQ8M.jpg'
  },
  {
    id: 4,
    nome: 'Jatobá',
    nomeCientifico: 'Hymenaea courbaril.',
    matriz: 'M 262',
    bioma: 'Cerrado, Mata Atlântica e Pampa',
    conservacao: 'Preocupante',
    classe: 'Secundária tardia',
    coleta: 'Jun-Jul',
    link: '/jatoba',
    gps: "https://www.google.com.br/maps/place/23%C2%B023'00.6%22S+47%C2%B037'25.0%22W/@-23.4053256,-47.625836,17z/data=!4m4!3m3!8m2!3d-23.3835!4d-47.6236",
    mudaDesc: 'Mudas de Jatobá atingem seu Porte médio adequado em 6 meses .',
    mudaImg: 'https://i.imgur.com/4Z4ZQ8M.jpg',
    sementeDes: 'Sementes de Jatoba podem ter cerca de 2 cm.',
    sementeImg: 'https://i.imgur.com/4Z4ZQ8M.jpg',
    arvoreDesc: 'Árvores de Jatobá podem ter cerca de 15-20 m.',
    arvoreImg: 'https://i.imgur.com/4Z4ZQ8M.jpg',
    florDesc: 'A Flor da ZXXXX floresce no periodo de Maio a Agosto.',
    florImg: 'https://i.imgur.com/4Z4ZQ8M.jpg'
  }
];

export default cadastroMatrizes;
